import { StyleSheet, Platform } from "react-native";
import { COLORS } from "@/src/constants/theme";

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.navy },
  scroll: { padding: 20, paddingTop: Platform.OS === "ios" ? 60 : 40 },
  center: { flex: 1, backgroundColor: COLORS.navy, justifyContent: "center", alignItems: "center" },
  emptyText: { color: COLORS.gray400, fontSize: 16 },
  backBtn: { marginTop: 16, paddingHorizontal: 20, paddingVertical: 10, backgroundColor: COLORS.crimson, borderRadius: 10 },
  backText: { color: COLORS.white, fontWeight: "700" },
  backRow: { flexDirection: "row", alignItems: "center", gap: 8, marginBottom: 20 },
  backLabel: { color: COLORS.white, fontSize: 16, fontWeight: "600" },
  statusCard: {
    backgroundColor: "rgba(245,166,35,0.1)", borderRadius: 16, padding: 16,
    marginBottom: 16, borderWidth: 1, borderColor: "rgba(245,166,35,0.2)", alignItems: "center",
  },
  statusLabel: { color: COLORS.gray400, fontSize: 12, marginBottom: 4 },
  statusValue: { color: COLORS.gold, fontSize: 20, fontWeight: "800" },
  card: {
    backgroundColor: "rgba(255,255,255,0.06)", borderRadius: 16, padding: 16,
    marginBottom: 12, borderWidth: 1, borderColor: "rgba(255,255,255,0.08)",
  },
  paidCard: { borderColor: "rgba(34,197,94,0.3)", backgroundColor: "rgba(34,197,94,0.08)" },
  cashCard: { borderColor: "rgba(245,166,35,0.3)", backgroundColor: "rgba(245,166,35,0.08)" },
  cardTitle: { color: COLORS.white, fontSize: 15, fontWeight: "700", marginBottom: 12 },
  paymentRow: { flexDirection: "row", alignItems: "center", gap: 10, marginBottom: 8 },
  paymentMethod: { color: COLORS.white, fontSize: 15, fontWeight: "600" },
  paymentNote: { color: COLORS.gray400, fontSize: 12 },
  paidBadge: { flexDirection: "row", alignItems: "center", gap: 6, backgroundColor: "rgba(34,197,94,0.15)", paddingHorizontal: 12, paddingVertical: 6, borderRadius: 8 },
  paidText: { color: COLORS.green, fontSize: 13, fontWeight: "700" },
  cashBadge: { flexDirection: "row", alignItems: "center", gap: 6, backgroundColor: "rgba(245,166,35,0.15)", paddingHorizontal: 12, paddingVertical: 6, borderRadius: 8 },
  cashText: { color: COLORS.gold, fontSize: 13, fontWeight: "700" },
  cashInputRow: { flexDirection: "row", alignItems: "center", backgroundColor: "rgba(255,255,255,0.08)", borderRadius: 12, paddingHorizontal: 14 },
  currencySign: { color: COLORS.gold, fontSize: 22, fontWeight: "800", marginRight: 6 },
  cashInput: { flex: 1, color: COLORS.white, fontSize: 22, fontWeight: "700", paddingVertical: 14 },
  cashHint: { color: COLORS.gray500, fontSize: 11, marginTop: 6 },
  infoRow: { flexDirection: "row", alignItems: "center", gap: 10, marginBottom: 8 },
  infoText: { color: COLORS.gray400, fontSize: 14 },
  tripRow: { flexDirection: "row", alignItems: "flex-start", gap: 12 },
  tripDot: { width: 10, height: 10, borderRadius: 5, marginTop: 4 },
  tripInfo: { flex: 1 },
  tripLabel: { color: COLORS.gray500, fontSize: 11, marginBottom: 2 },
  tripAddress: { color: COLORS.white, fontSize: 14, fontWeight: "500" },
  tripLine: { width: 2, height: 20, backgroundColor: "rgba(255,255,255,0.1)", marginLeft: 4, marginVertical: 4 },
  rideGrid: { flexDirection: "row", flexWrap: "wrap", gap: 12 },
  rideItem: {
    width: "46%", backgroundColor: "rgba(255,255,255,0.04)", borderRadius: 12,
    padding: 12, alignItems: "center",
  },
  rideValue: { color: COLORS.white, fontSize: 15, fontWeight: "700", marginTop: 6 },
  rideLabel: { color: COLORS.gray500, fontSize: 11, marginTop: 2 },
  actionsWrap: { gap: 10, marginTop: 8 },
  actionBtn: {
    flexDirection: "row", alignItems: "center", justifyContent: "center",
    gap: 10, paddingVertical: 16, borderRadius: 14,
  },
  actionText: { color: COLORS.white, fontSize: 16, fontWeight: "700" },
  navBtn: {
    flexDirection: "row", alignItems: "center", justifyContent: "center",
    gap: 8, backgroundColor: "#3B82F6", borderRadius: 12, paddingVertical: 12, marginTop: 14,
  },
  navBtnText: { color: COLORS.white, fontWeight: "700", fontSize: 14 },
});
